{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  ".result": "configured",
  "android": null,
  "language": "android",
  "components": [
    "build-tools-25.0.0",
    "android-25",
    "sys-img-armeabi-v7a-android-22",
    "sys-img-armeabi-v7a-android-17"
  ],
  "before_install": [
    "chmod +x gradlew"
  ]
}